### ISSUE TITLE
 Unable to locate package WORKDIR

### ISSUE THREAD

**Issue by d3diva** [coderjourney/03-learn-to-use-docker-in-development#3]
hi kieth,

cool tutorial loved it,
but hit a block, getting the following error

**E: Unable to locate package WORKDIR
E: Unable to locate package /usr/src**

and was also getting 
**rm: cannot remove '/var/lib/apt/lists': Directory not empty**
but commented it out 

if you please help figure it out it would be of great help
thank you in advance

**Comment by keiththomps** [comment]
Can you paste your Dockerfile in here for me to take a look at? If I had to guess, it looks like you might have a `RUN` before the `WORKDIR` (on the same line).

The error regarding `rm: cannot remove` is likely because the call to `rm` is missing the `-rf` flag.

**Comment by d3diva** [comment]
my Dockerfile

FROM ruby:2.3

RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
    postgresql-client \
    # && rm -rf /var/lib/apt/lists

WORKDIR  /usr/src/app
COPY Gemfile* ./
RUN bundle install
COPY . .

EXPOSE 3000
CMD rails server -b 0.0.0.0 -P /tmp/server.pid

**Comment by d3diva** [comment]
hi,
my **blog** folder was **locked**, changed the permission and **commented out && rm -rf /var/lib/apt/lists**
and it worked fine
any idea how 'blog' folder got locked
thank you
