### ISSUE TITLE
Template is missing

### ISSUE THREAD

**Issue by mskadu** [coderjourney/03-learn-to-use-docker-in-development#4]
hi there, agree that this is a useful tutorial. So thanks :)

I am looking at the final bit of Part 1 where you make changes to config/routes.rb and  app/controllers/wecome_controller.rb. I have verified my changes are exact - even used copies of your github files. But when I make the changes and refresh the browser I get a "Template is missing" error

![screenshot from 2017-05-09 14-38-15](https://cloud.githubusercontent.com/assets/23300/25853579/35b16c38-34c5-11e7-9c63-a20b1bdaa840.png)

Any suggestions?

**Comment by keiththomps** [comment]
I would suggest changing "text:" to be "plain:" (the "text" option was deprecated and renamed, but this isn't causing the issue). Restart your Docker container and see if the view renders properly. It's possible that you have a code reloading issue that I've seen when working with Docker. Make sure that you have [this line](https://github.com/coderjourney/03-learn-to-use-docker-in-development/blob/master/blog/config/environments/development.rb#L53) commented out.

**Comment by mskadu** [comment]
Bingo! Much appreciated :1st_place_medal:
